name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'concepts/**.md'
      - 'imgs/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - name: Convert Markdown To PDF 
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: concepts
          output_dir: pdfs
          images_dir: imgs
          image_import: ./imgs
          build_html: false

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Build PDFs"
          echo "${{ secrets.PAT }}" | git push origin HEAD:main