name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'concepts/**.md'
      - 'imgs/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: List files in concepts directory
        run: ls concepts
        
      - name: Convert Markdown To PDF 
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: concepts
          output_dir: pdfs_actions
          images_dir: imgs
          image_import: ./imgs
          build_html: false
          
      - name: List files in pdfs directory
        run: ls pdfs_actions
      
      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs_actions